name: react
version: 5.3.0
authors:
  - Samuel Hap√°k <samuel.hapak@gmail.com>
  - Greg Littlefield <greg.littlefield@workiva.com>
  - Claire Sarsam <claire.sarsam@workiva.com>
  - Aaron Lademann <aaron.lademann@workiva.com>
  - Keal Jones <keal.jones@workiva.com>
  - Joe Bingham <joe.bingham@workiva.com>
  - Sydney Jodon <sydney.jodon@workiva.com>
description: Bindings of the ReactJS library for building interactive interfaces.
homepage: https://github.com/cleandart/react-dart
environment:
  sdk: '>=2.4.0 <3.0.0'
dependencies:
  js: ^0.6.0
  meta: ^1.1.6
dev_dependencies:
  args: ^1.5.1
  build_runner: ^1.6.5
  build_test: ^0.10.8
  build_web_compilers: ^2.1.4
  dependency_validator: ^1.2.0
  matcher: ^0.12.5
  test: ^1.6.5
  semver_audit:
    hosted:
      name: semver_audit
      url: https://pub.workiva.org
    version: ^1.0.0