name: react
version: 6.1.6
description: Bindings of the ReactJS library for building interactive interfaces.
homepage: https://github.com/cleandart/react-dart
environment:
  sdk: ">=2.11.0 <3.0.0"
dependencies:
  js: ^0.6.0
  meta: ^1.1.6
dev_dependencies:
  args: ">=1.5.1 <3.0.0"
  build_runner: ">=1.6.5 <3.0.0"
  build_test: ">=0.10.8 <3.0.0"
  build_web_compilers: ">=2.12.0 <4.0.0"
  dependency_validator: ">=2.0.0 <4.0.0"
  matcher: ^0.12.5
  mockito: ">=4.1.1 <6.0.0"
  test: ^1.6.5
