name: react
version: 5.0.0-dev.alpha.1
authors:
  - Samuel Hap√°k <samuel.hapak@gmail.com>
  - Greg Littlefield <greg.littlefield@workiva.com>
  - Claire Sarsam <claire.sarsam@workiva.com>
  - Aaron Lademann <aaron.lademann@workiva.com>
description: Bindings of the ReactJS library for building interactive interfaces.
homepage: https://github.com/cleandart/react-dart
environment:
  sdk: '>=2.0.0-dev.0 <=2.0.0-dev.49.0'
dependencies:
  js: ^0.6.0
dev_dependencies:
  test: ^0.12.32+1

transformers:
- test/pub_serve:
    $include: test/**_test.dart
