name: react
version: 3.1.0
author: Clean Team <clean@vacuumlabs.com>
description: Bindings of the ReactJS library for building interactive interfaces.
homepage: http://cleandart.github.io/react-dart/
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.11.0'
  js: '^0.6.0'
dev_dependencies:
  test: '^0.12.18+1'
