name: react
version: 6.1.8
description: Bindings of the ReactJS library for building interactive interfaces.
homepage: https://github.com/cleandart/react-dart
environment:
  sdk: ">=2.11.0 <3.0.0"
dependencies:
  js: ^0.6.0
  meta: ^1.1.6
dev_dependencies:
  args: ">=1.5.1 <3.0.0"
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^3.0.0
  dependency_validator: ^3.2.2
  matcher: ^0.12.11
  mockito: ">=4.1.1 <6.0.0"
  test: ^1.17.12
